import type { INodeProperties } from 'n8n-workflow';
import { CANDIDATE_MODES, USER_MODES } from './SharedFields';

export const candidateOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: { resource: ['candidate'] },
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a candidate',
				description: 'Create a new candidate',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a candidate',
				description: 'Retrieve a candidate by ID',
			},
			{
				name: 'Get Many',
				value: 'getMany',
				action: 'Get many candidates',
				description: 'Retrieve a list of candidates',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a candidate',
				description: 'Update a candidate',
			},
		],
		default: 'create',
	},
];

const GENDER_OPTIONS = [
	{ name: 'Female', value: 'female' },
	{ name: 'Male', value: 'male' },
	{ name: 'Other', value: 'other' },
	{ name: 'Unknown', value: 'unknown' },
];

const SOURCE_TYPE_OPTIONS = [
	{ name: 'Agency', value: 'agency' },
	{ name: 'Applied', value: 'applied' },
	{ name: 'Other', value: 'other' },
	{ name: 'Referred', value: 'referred' },
	{ name: 'Sourced', value: 'sourced' },
];

export const candidateFields: INodeProperties[] = [
	{
		displayName: 'Candidate ID',
		name: 'candidateId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		hint: 'Use a Candidate Get Many step upstream to retrieve IDs',
		modes: CANDIDATE_MODES,
		displayOptions: {
			show: { resource: ['candidate'], operation: ['get'] },
		},
		description: 'Numeric ID of the candidate',
	},

	// ── GET MANY ──────────────────────────────────────────────────────────
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: { resource: ['candidate'], operation: ['getMany'] },
		},
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 100 },
		default: 10,
		displayOptions: {
			show: { resource: ['candidate'], operation: ['getMany'], returnAll: [false] },
		},
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: { resource: ['candidate'], operation: ['getMany'] },
		},
		options: [
			{
				displayName: 'Address',
				name: 'address',
				type: 'string',
				default: '',
				description: 'Filter by address (partial match)',
			},
			{
				displayName: 'Birth Date (From)',
				name: 'birth_date__gte',
				type: 'dateTime',
				default: '',
				description: 'Return candidates born on or after this date',
			},
			{
				displayName: 'Birth Date (To)',
				name: 'birth_date__lte',
				type: 'dateTime',
				default: '',
				description: 'Return candidates born on or before this date',
			},
			{
				displayName: 'Candidate Location',
				name: 'candidate_location',
				type: 'string',
				default: '',
				description: 'Filter by candidate location',
			},
			{
				displayName: 'Candidate Tags',
				name: 'candidate_tags',
				type: 'string',
				default: '',
				description: 'Filter by tag ID(s)',
			},
			{
				displayName: 'Created At (From)',
				name: 'created_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return candidates created on or after this date',
			},
			{
				displayName: 'Created At (To)',
				name: 'created_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return candidates created on or before this date',
			},
			{
				displayName: 'Current Company',
				name: 'current_company',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Current Position',
				name: 'current_position',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				description: 'Filter by description text (partial match)',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				default: '',
				placeholder: 'name@email.com',
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				description: 'Filter by the external system ID',
			},
			{
				displayName: 'Full Name',
				name: 'full_name',
				type: 'string',
				default: '',
				description: 'Filter by name (partial match)',
			},
			{
				displayName: 'Gender',
				name: 'gender',
				type: 'options',
				default: 'unknown',
				options: GENDER_OPTIONS,
			},
			{
				displayName: 'ID',
				name: 'id',
				type: 'number',
				default: '',
				description: 'Filter by exact candidate ID',
			},
{
				displayName: 'Latest Degree',
				name: 'latest_degree',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Latest University',
				name: 'latest_university',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Owner',
				name: 'owner_id',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				description: 'Filter by owner user',
				modes: USER_MODES,
			},
			{
				displayName: 'Phone Number',
				name: 'phone_number',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Source Type',
				name: 'source_type',
				type: 'options',
				default: 'sourced',
				options: SOURCE_TYPE_OPTIONS,
				description: 'Filter by source type',
			},
			{
				displayName: 'Updated At (From)',
				name: 'updated_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return candidates updated on or after this date',
			},
			{
				displayName: 'Updated At (To)',
				name: 'updated_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return candidates updated on or before this date',
			},
		],
	},

	// ── CREATE ────────────────────────────────────────────────────────────
	{
		displayName: 'Full Name',
		name: 'fullName',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: { resource: ['candidate'], operation: ['create'] },
		},
		description: "The candidate's full name",
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['candidate'], operation: ['create'] },
		},
		options: [
			{
				displayName: 'Address',
				name: 'address',
				type: 'string',
				default: '',
				description: 'Full address of the candidate',
			},
			{
				displayName: 'Birth Date',
				name: 'birth_date',
				type: 'dateTime',
				default: '',
				description: "Candidate's date of birth",
			},
			{
				displayName: 'Consent',
				name: 'consent',
				type: 'boolean',
				default: false,
				description:
					'Whether the candidate has given permission to use their data (GDPR / LGPD / CCPA)',
			},
			{
				displayName: 'Current Company',
				name: 'current_company',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Current Department',
				name: 'current_department',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Current Position',
				name: 'current_position',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Custom Fields',
				name: 'custom_fields',
				type: 'json',
				default: '{}',
				description:
					'Custom field values as a JSON object. Must be a full object — partial updates will overwrite existing values.',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
				description: 'Plain text description of the candidate',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				description: 'ID of the candidate in the API consumer system',
			},
			{
				displayName: 'Gender',
				name: 'gender',
				type: 'options',
				default: 'unknown',
				options: GENDER_OPTIONS,
			},
			{
				displayName: 'Latest Degree',
				name: 'latest_degree',
				type: 'string',
				default: '',
				description: 'Most recent degree obtained by the candidate',
			},
			{
				displayName: 'Latest University',
				name: 'latest_university',
				type: 'string',
				default: '',
				description: 'Most recent university attended by the candidate',
			},
			{
				displayName: 'Owner',
				name: 'owner',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				description: 'User who owns this candidate record. Defaults to the API token owner.',
				modes: USER_MODES,
			},
			{
				displayName: 'Phone Number',
				name: 'phone_number',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Source Other',
				name: 'source_other',
				type: 'string',
				default: '',
				description: 'Additional source detail — only used when Source Type is "Other"',
			},
			{
				displayName: 'Source Type',
				name: 'source_type',
				type: 'options',
				default: 'sourced',
				options: SOURCE_TYPE_OPTIONS,
				description: 'Origin of the candidate',
			},
			{
				displayName: 'Zip Code',
				name: 'zipcode',
				type: 'string',
				default: '',
				description: 'Postal code for the candidate address',
			},
		],
	},

	// ── UPDATE ────────────────────────────────────────────────────────────
	{
		displayName: 'Candidate ID',
		name: 'candidateId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		hint: 'Use a Candidate Get Many step upstream to retrieve IDs',
		modes: CANDIDATE_MODES,
		displayOptions: {
			show: { resource: ['candidate'], operation: ['update'] },
		},
		description: 'Numeric ID of the candidate to update',
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['candidate'], operation: ['update'] },
		},
		options: [
			{
				displayName: 'Address',
				name: 'address',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Birth Date',
				name: 'birth_date',
				type: 'dateTime',
				default: '',
			},
			{
				displayName: 'Consent',
				name: 'consent',
				type: 'boolean',
				default: false,
				description:
					'Whether the candidate has given permission to use their data (GDPR / LGPD / CCPA)',
			},
			{
				displayName: 'Current Company',
				name: 'current_company',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Current Department',
				name: 'current_department',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Current Position',
				name: 'current_position',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Custom Fields',
				name: 'custom_fields',
				type: 'json',
				default: '{}',
				description:
					'Custom field values as a JSON object. Must be a full object — partial updates will overwrite existing values.',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				description: 'ID of the candidate in the API consumer system',
			},
			{
				displayName: 'Full Name',
				name: 'full_name',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Gender',
				name: 'gender',
				type: 'options',
				default: 'unknown',
				options: GENDER_OPTIONS,
			},
			{
				displayName: 'Latest Degree',
				name: 'latest_degree',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Latest University',
				name: 'latest_university',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Owner',
				name: 'owner',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				modes: USER_MODES,
			},
			{
				displayName: 'Phone Number',
				name: 'phone_number',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Source Other',
				name: 'source_other',
				type: 'string',
				default: '',
				description: 'Additional source detail — only used when Source Type is "Other"',
			},
			{
				displayName: 'Source Type',
				name: 'source_type',
				type: 'options',
				default: 'sourced',
				options: SOURCE_TYPE_OPTIONS,
				description: 'Origin of the candidate',
			},
			{
				displayName: 'Zip Code',
				name: 'zipcode',
				type: 'string',
				default: '',
			},
		],
	},
];
