import type { INodeProperties } from 'n8n-workflow';
import { JOB_MODES, ORGANIZATION_MODES, USER_MODES } from './SharedFields';

export const jobOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: { resource: ['job'] },
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a job',
				description: 'Create a new job posting',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a job',
				description: 'Retrieve a job by ID',
			},
			{
				name: 'Get Many',
				value: 'getMany',
				action: 'Get many jobs',
				description: 'Retrieve a list of jobs',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a job',
				description: 'Update a job posting',
			},
		],
		default: 'getMany',
	},
];

export const jobFields: INodeProperties[] = [
	{
		displayName: 'Job ID',
		name: 'jobId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		hint: 'Use a Job Get Many step upstream to retrieve IDs',
		modes: JOB_MODES,
		displayOptions: {
			show: { resource: ['job'], operation: ['get'] },
		},
		description: 'Numeric ID of the job',
	},

	// ── GET MANY ─────────────────────────────────────────────────────────
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: { resource: ['job'], operation: ['getMany'] },
		},
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 100 },
		default: 10,
		displayOptions: {
			show: { resource: ['job'], operation: ['getMany'], returnAll: [false] },
		},
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: { resource: ['job'], operation: ['getMany'] },
		},
		options: [
			{
				displayName: 'Address',
				name: 'address',
				type: 'string',
				default: '',
				description: 'Filter by address (partial match)',
			},
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Close At (From)',
				name: 'close_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs closed on or after this date',
			},
			{
				displayName: 'Close At (To)',
				name: 'close_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs closed on or before this date',
			},
			{
				displayName: 'Contract Details',
				name: 'contract_details',
				type: 'options',
				default: '',
				options: [
					{ name: 'Apprenticeship', value: 'apprenticeship' },
					{ name: 'Consultancy', value: 'consultancy' },
					{ name: 'Contractor', value: 'contractor' },
					{ name: 'Freelance', value: 'freelance' },
					{ name: 'Full Time', value: 'full_time' },
					{ name: 'Internship', value: 'internship' },
					{ name: 'Part Time', value: 'part_time' },
					{ name: 'Temporary', value: 'temporary' },
				],
			},
			{
				displayName: 'Created At (From)',
				name: 'created_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs created on or after this date',
			},
			{
				displayName: 'Created At (To)',
				name: 'created_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs created on or before this date',
			},
			{
				displayName: 'Creator',
				name: 'creator_id',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				description: 'Filter by creator user',
				modes: USER_MODES,
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				description: 'Filter by the external system ID',
			},
			{
				displayName: 'Frequency',
				name: 'frequency',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Headcount',
				name: 'headcount',
				type: 'number',
				default: '',
				description: 'Filter by exact headcount',
			},
			{
				displayName: 'ID',
				name: 'id',
				type: 'number',
				default: '',
				description: 'Filter by exact job ID',
			},
			{
				displayName: 'Is Published',
				name: 'is_published',
				type: 'boolean',
				default: true,
				description: 'Whether to filter by published/unpublished jobs',
			},
			{
				displayName: 'Is Remote',
				name: 'is_remote',
				type: 'boolean',
				default: false,
				description: 'Whether to filter by remote jobs',
			},
			{
				displayName: 'Open At (From)',
				name: 'open_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs opened on or after this date',
			},
			{
				displayName: 'Open At (To)',
				name: 'open_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs opened on or before this date',
			},
			{
				displayName: 'Organization',
				name: 'organization',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				description: 'Filter by organization',
				modes: ORGANIZATION_MODES,
			},
			{
				displayName: 'Owner',
				name: 'owner_id',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				description: 'Filter by owner user',
				modes: USER_MODES,
			},
			{
				displayName: 'Position Name',
				name: 'position_name',
				type: 'string',
				default: '',
				description: 'Filter by position name (partial match)',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: '',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Lost', value: 'lost' },
					{ name: 'On Hold', value: 'on_hold' },
					{ name: 'Won', value: 'won' },
				],
			},
			{
				displayName: 'Updated At (From)',
				name: 'updated_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs updated on or after this date',
			},
			{
				displayName: 'Updated At (To)',
				name: 'updated_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs updated on or before this date',
			},
		],
	},

	// ── CREATE ───────────────────────────────────────────────────────────
	{
		displayName: 'Position Name',
		name: 'positionName',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: { resource: ['job'], operation: ['create'] },
		},
		description: 'The title of the job position',
	},
	{
		displayName: 'Organization',
		name: 'organization',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		modes: ORGANIZATION_MODES,
		displayOptions: {
			show: { resource: ['job'], operation: ['create'] },
		},
		description: 'The organization this job belongs to',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['job'], operation: ['create'] },
		},
		options: [
			{
				displayName: 'Address',
				name: 'address',
				type: 'string',
				default: '',
				description: 'Address of the office where the job will take place',
			},
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				default: '',
				description: 'City of the office where the job will take place',
			},
			{
				displayName: 'Contract Details',
				name: 'contract_details',
				type: 'options',
				default: 'full_time',
				options: [
					{ name: 'Apprenticeship', value: 'apprenticeship' },
					{ name: 'Consultancy', value: 'consultancy' },
					{ name: 'Contractor', value: 'contractor' },
					{ name: 'Freelance', value: 'freelance' },
					{ name: 'Full Time', value: 'full_time' },
					{ name: 'Internship', value: 'internship' },
					{ name: 'Part Time', value: 'part_time' },
					{ name: 'Temporary', value: 'temporary' },
				],
				description: 'Type of employment contract',
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				default: '',
				description: 'Country of the office where the job will take place',
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'options',
				default: '',
				typeOptions: { loadOptionsMethod: 'getCurrencies' },
				description: 'Currency for the salary range',
			},
			{
				displayName: 'Custom Fields',
				name: 'custom_fields',
				type: 'json',
				default: '{}',
				description:
					'Custom field values as a JSON object. Must be a full object — partial updates will overwrite existing values.',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
				description: 'Description of the job',
			},
			{
				displayName: 'Expected Close At',
				name: 'expected_close_at',
				type: 'dateTime',
				default: '',
				description: 'Expected date when the position will be closed/filled',
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				description: 'ID of the job in the API consumer system',
			},
			{
				displayName: 'Frequency',
				name: 'frequency',
				type: 'string',
				default: '',
				description: 'Salary payment frequency (e.g. monthly, annual)',
			},
			{
				displayName: 'Headcount',
				name: 'headcount',
				type: 'number',
				default: 1,
				description: 'Number of open positions',
			},
			{
				displayName: 'Industry',
				name: 'industry',
				type: 'options',
				default: '',
				typeOptions: { loadOptionsMethod: 'getIndustries' },
				description: 'Industry for this job',
			},
			{
				displayName: 'Is Pinned In Career Page',
				name: 'is_pinned_in_career_page',
				type: 'boolean',
				default: false,
				description: 'Whether the job is pinned at the top of the career page',
			},
			{
				displayName: 'Is Published',
				name: 'is_published',
				type: 'boolean',
				default: false,
				description: 'Whether to publish the job on the career page',
			},
			{
				displayName: 'Is Remote',
				name: 'is_remote',
				type: 'boolean',
				default: false,
				description: 'Whether this is a remote position',
			},
			{
				displayName: 'Is Salary Visible',
				name: 'is_salary_visible',
				type: 'boolean',
				default: false,
				description: 'Whether salary information is displayed to candidates',
			},
			{
				displayName: 'Owner',
				name: 'owner',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				description: 'User who owns this job record',
				modes: USER_MODES,
			},
			{
				displayName: 'Salary Max',
				name: 'salary_max',
				type: 'string',
				default: '',
				description: 'Maximum salary for this position',
			},
			{
				displayName: 'Salary Min',
				name: 'salary_min',
				type: 'string',
				default: '',
				description: 'Minimum salary for this position',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
				description: 'State of the office where the job will take place',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: 'active',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Lost', value: 'lost' },
					{ name: 'On Hold', value: 'on_hold' },
					{ name: 'Won', value: 'won' },
				],
				description: 'Status of the job',
			},
			{
				displayName: 'Zip Code',
				name: 'zipcode',
				type: 'string',
				default: '',
			},
		],
	},

	// ── UPDATE ───────────────────────────────────────────────────────────
	{
		displayName: 'Job ID',
		name: 'jobId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		hint: 'Use a Job Get Many step upstream to retrieve IDs',
		modes: JOB_MODES,
		displayOptions: {
			show: { resource: ['job'], operation: ['update'] },
		},
		description: 'Numeric ID of the job to update',
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['job'], operation: ['update'] },
		},
		options: [
			{
				displayName: 'Address',
				name: 'address',
				type: 'string',
				default: '',
			},
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Contract Details',
				name: 'contract_details',
				type: 'options',
				default: '',
				options: [
					{ name: 'Apprenticeship', value: 'apprenticeship' },
					{ name: 'Consultancy', value: 'consultancy' },
					{ name: 'Contractor', value: 'contractor' },
					{ name: 'Freelance', value: 'freelance' },
					{ name: 'Full Time', value: 'full_time' },
					{ name: 'Internship', value: 'internship' },
					{ name: 'Part Time', value: 'part_time' },
					{ name: 'Temporary', value: 'temporary' },
				],
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'options',
				default: '',
				typeOptions: { loadOptionsMethod: 'getCurrencies' },
			},
			{
				displayName: 'Custom Fields',
				name: 'custom_fields',
				type: 'json',
				default: '{}',
				description:
					'Custom field values as a JSON object. Must be a full object — partial updates will overwrite existing values.',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
			},
			{
				displayName: 'Expected Close At',
				name: 'expected_close_at',
				type: 'dateTime',
				default: '',
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Frequency',
				name: 'frequency',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Headcount',
				name: 'headcount',
				type: 'number',
				default: 1,
			},
			{
				displayName: 'Industry',
				name: 'industry',
				type: 'options',
				default: '',
				typeOptions: { loadOptionsMethod: 'getIndustries' },
			},
			{
				displayName: 'Is Pinned In Career Page',
				name: 'is_pinned_in_career_page',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Is Published',
				name: 'is_published',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Is Remote',
				name: 'is_remote',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Is Salary Visible',
				name: 'is_salary_visible',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Owner',
				name: 'owner',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				modes: USER_MODES,
			},
			{
				displayName: 'Position Name',
				name: 'position_name',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Salary Max',
				name: 'salary_max',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Salary Min',
				name: 'salary_min',
				type: 'string',
				default: '',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: '',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Lost', value: 'lost' },
					{ name: 'On Hold', value: 'on_hold' },
					{ name: 'Won', value: 'won' },
				],
			},
			{
				displayName: 'Zip Code',
				name: 'zipcode',
				type: 'string',
				default: '',
			},
		],
	},
];
